name: Publish v1 docker image
on:
  push:
    branches:
      - "release-v1.0.0"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compute new docker image tag
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF_NAME})" >> "$GITHUB_ENV"
          echo "docker_tag=$(echo v1)-$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          push: true
          tags: |
            ghcr.io/allenneuraldynamics/aind-metadata-mapper:${{ env.docker_tag }}
