name: Lint and run tests

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11' ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: | 
        python -m pip install -e .[dev]
    - name: Run linter checks
      run: flake8 . && interrogate --verbose .
    - name: Run tests and coverage
      run: coverage run -m unittest discover && coverage report
  integration_tests:
    runs-on: ubuntu-latest
    env:
      AWS_DATA_SCHEMA_ROLE: ${{ secrets.AWS_DATA_SCHEMA_ROLE_DEV }}
      AWS_DATA_SCHEMA_BUCKET: ${{ vars.AWS_DATA_SCHEMA_BUCKET_DEV }}
      AWS_REGION: ${{ vars.AWS_REGION_DEV }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install dependencies
        run:
          python -m pip install -e .[all]
          python -m pip install -e s3fs
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_DATA_SCHEMA_ROLE_DEV }}
          role-session-name: github-integration-test-session
          aws-region: ${{ env.AWS_REGION }}
      - name: run integration tests
        run:
          python -m tests/integraton/test_bergamo/test_session





